package transferobjects;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Question {
    private String givenQuestion; //the Question given by the User
    private List<String> givenAnswers; //the correct Answer given by the User
    private List<String> wrongAnswers; //autogenerated Wrong answers by AI based on @givenQuestion

}
